### ISSUE TITLE
Segmentation Fault on sandbox exit after preemption

### ISSUE THREAD

**Issue by bushidocodes** [gwsystems/sledge-serverless-framework#66]
The runtime currently experiences a mysterious segfault when a sandbox is preempted for another with a earlier deadline while running the minheap-based request queues and runqueues..

This remains unsolved, but a temporary band-aide has been added which prevents the segfault. See the section `Temporary Workaround` below for details. Be sure to comment out `assert(0)` if you want to recreate this bug.

This can be reproduced by the test infrastructure in `runtime/tests/preemption.` Start `debug.sh` to start the runtime under GDB, and then run `client1.sh`. This will run indefinitely and should not encounter an error. Then run `client2.sh`, which adds requests with an earlier deadline, forcing preemption.

In GDB, this triggers an error roughly as follows:

```
Thread 4 "awsmrt" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5bd1700 (LWP 22007)]
0x00000000004092c1 in current_sandbox_main () at src/sandbox.c:278
278             worker_thread_on_sandbox_exit(sandbox);
(gdb) back
#0  0x00000000004092c1 in current_sandbox_main () at src/sandbox.c:278
#1  0x0000000000000000 in ?? ()
(gdb)
```

Where `sandbox.c:278` is as follows:
```c
worker_thread_on_sandbox_exit(sandbox);
```

Based on an investigation of `objdump -Shrtl`, this is compiled into the following assembly:

```
current_sandbox_main():
/awsm/runtime/src/sandbox.c:278
  4092b5:       4c 89 e7                mov    %r12,%rdi
  4092b8:       48 83 c4 48             add    $0x48,%rsp
  4092bc:       5b                      pop    %rbx
  4092bd:       41 5c                   pop    %r12
  4092bf:       41 5d                   pop    %r13
  4092c1:       41 5e                   pop    %r14
  4092c3:       41 5f                   pop    %r15
  4092c5:       5d                      pop    %rbp
  4092c6:       e9 05 18 00 00          jmpq   40aad0 <worker_thread_on_sandbox_exit>
  4092cb:       bf 31 78 41 00          mov    $0x417831,%edi
  4092d0:       be 95 77 41 00          mov    $0x417795,%esi
  4092d5:       b9 dd 78 41 00          mov    $0x4178dd,%ecx
  4092da:       ba 3a 00 00 00          mov    $0x3a,%edx
  4092df:       e8 ec b1 ff ff          callq  4044d0 <__assert_fail@plt>
```

So the offending line of assembly is:

```
  4092c1:       41 5e                   pop    %r14
```

Per @phanikishoreg,  "the crash happened because it was at the end of the execution, trying to pop something off the stack that didn't look like a valid stack pointer address or to put it another way, the stack pointer address on crash looked like was aligned to the PAGE_SIZE (likely start of the stack), which is likely because we are likely off by a few bytes or something."

## Temporary Workaround

By adding `assert(0)` after the call to `worker_thread_on_sandbox_exit(sandbox)`, certain compiler optimizations were prevented, and this seems to prevent the segfault, as the offending pop instruction is move after the function call, which is never actually reacted in the codebase because of the context switch triggered by `worker_thread_on_sandbox_exit`. Notice that the resulting assembly no longer has the ` pop    %r14` instruction, and that various move instructions are now executed as part of the `assert(0)` on line 283. Because `worker_thread_on_sandbox_exit` never returns, 409287 - 2092b4 is never executed.

```
/awsm/runtime/src/sandbox.c:278
  40927f:       4c 89 f7                mov    %r14,%rdi
  409282:       e8 59 18 00 00          callq  40aae0 <worker_thread_on_sandbox_exit>
/awsm/runtime/src/sandbox.c:283
  409287:       bf 7b 61 41 00          mov    $0x41617b,%edi
  40928c:       be 24 6a 41 00          mov    $0x416a24,%esi
  409291:       b9 77 6a 41 00          mov    $0x416a77,%ecx
  409296:       ba 1b 01 00 00          mov    $0x11b,%edx
  40929b:       e8 30 b2 ff ff          callq  4044d0 <__assert_fail@plt>
  4092a0:       bf 7b 78 41 00          mov    $0x41787b,%edi
  4092a5:       be df 77 41 00          mov    $0x4177df,%esi
  4092aa:       b9 27 79 41 00          mov    $0x417927,%ecx
  4092af:       ba 3a 00 00 00          mov    $0x3a,%edx
  4092b4:       e8 17 b2 ff ff          callq  4044d0 <__assert_fail@plt>
```

**Comment by bushidocodes** [comment]
The `assert(0)` mentioned above as the fix for the segfault is currently in the `done` block of `current_sandbox_start`:


```c
void
current_sandbox_start(void)
{
<snip>
done:
	/* Cleanup connection and exit sandbox */
	generic_thread_dump_lock_overhead();
	scheduler_yield();

	/* This assert prevents a segfault discussed in
	 * https://github.com/phanikishoreg/awsm-Serverless-Framework/issues/66
	 */
	assert(0);
err:
	debuglog("%s", error_message);
	assert(sandbox->state == SANDBOX_RUNNING);

	sandbox_close_http(sandbox);
	sandbox_set_as_error(sandbox, SANDBOX_RUNNING);
	goto done;
}
```

**Comment by bushidocodes** [comment]
My impression is that this bug was fixed by the latest scheduler redesign. Closing.
